# Generated by Django 4.2 on 2023-05-25 07:36

import common.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_re_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=common.constants.RolesEnum['USER'], max_length=31),
        ),
    ]
