# Generated by Django 4.2 on 2023-05-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='re_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
