# Generated by Django 4.2 on 2023-05-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_re_token_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='re_token',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=31),
        ),
    ]
