# Generated by Django 4.2 on 2023-05-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cate',
        ),
    ]
